included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - ../KognitaCore/Sources
  - ../KognitaAPI/Sources
  - ../KognitaViews/Sources
excluded:
  - .build/checkouts

disabled_rules:
  - line_length

opt_in_rules:
  - missing_docs

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try: warning

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error

function_body_length:
  warning: 70
  error: 140

# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

nesting:
  type_level: 4

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
