version: '3'
services:
  kognita-web:
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    environment:
      - BUILD_TYPE=DEV
      - ROOT_URL=http://localhost:8080
      - MAILGUN_DOMAIN=depe
      - MAILGUN_KEY=dd
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=vapor
      - DATABASE_PASSWORD=password
      - DATABASE_DB=vapor
      - VAPOR_MIGRATION=true
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=vapor
      - POSTGRES_USER=vapor
      - POSTGRES_PASSWORD=password
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432
