name: Swift

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - rc/*
      - 1.*

jobs:
  bionic-job:
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
    - name: Run unit tests
      if: github.ref != 'refs/heads/master'
      env:
        BUILD_TYPE: DEV
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_DB: postgres
        DATABASE_HOSTNAME: localhost
      run: swift test
    - name: Run unit tests master
      if: github.ref == 'refs/heads/master'
      env:
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_DB: postgres
        DATABASE_HOSTNAME: localhost
      run: swift test
    - name: Build library in release mode
      if: github.ref == 'refs/heads/master'
      run: swift build -c release
    - name: Release new version
      uses: MatsMoll/action-finch@master
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
        FINCH_CONFIG: CI/finch-config.yml
