name: Swift Tests

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - rc/*
      - 1.*

jobs:
  container-job:
    container:
      image: swift:5.1.2-bionic
      env:
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_DB: postgres
        DATABASE_HOSTNAME: postgres
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run unit tests
      run: |
        apt-get -qq update && apt-get install -y \
          libssl-dev zlib1g-dev \
          && rm -r /var/lib/apt/lists/*
        swift test
    - name: Build library in release mode
      run: swift build -c release
      if: github.ref == 'master'
    - name: Release new version
      run: bash ./CI/release-version.sh
      if: github.ref == 'master'
